# Generated by Django 5.1.3 on 2025-05-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
