# Generated by Django 5.1.3 on 2024-12-03 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='identification_number',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='identification_type',
            field=models.CharField(blank=True, choices=[('id', 'National ID'), ('passport', 'Passport'), ('workPermit', 'Work Permit'), ('militaryId', 'Military ID'), ('driversLicense', "Driver's License")], max_length=20, null=True),
        ),
    ]
