# Generated by Django 5.1.3 on 2025-05-26 08:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_lease_account_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentperiodstatus',
            name='water_bill_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Water bill amount for this rental period', max_digits=10),
        ),
        migrations.AddField(
            model_name='rentperiodstatus',
            name='water_units_used',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Water units used during this period', max_digits=8),
        ),
        migrations.AddField(
            model_name='unit',
            name='water_bill_last_updated',
            field=models.DateField(blank=True, help_text='Date when water bill was last updated', null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='water_price_per_unit',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Price per water unit', max_digits=8),
        ),
        migrations.AddField(
            model_name='unit',
            name='water_units_used',
            field=models.DecimalField(decimal_places=2, default=2.0, help_text='Water units consumed this month (defaults to 2 units)', max_digits=8),
        ),
        migrations.CreateModel(
            name='WaterBillUpdate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('units_used', models.DecimalField(decimal_places=2, help_text='Water units consumed', max_digits=8)),
                ('price_per_unit', models.DecimalField(decimal_places=2, help_text='Price per water unit', max_digits=8)),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='Total water bill amount', max_digits=10)),
                ('billing_month', models.DateField(help_text='Month for this water bill')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_updates', to='api.unit')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='water_bill_updates', to='api.profile')),
            ],
            options={
                'unique_together': {('unit', 'billing_month')},
            },
        ),
    ]
