# Generated by Django 5.1.3 on 2024-12-03 05:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customuser_identification_number_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('user_type', models.CharField(choices=[('ADMIN', 'Property Owner'), ('MANAGER', 'Property Manager'), ('CLERK', 'Clerk')], default='CLERK', max_length=10)),
                ('identification_type', models.CharField(blank=True, choices=[('id', 'National ID'), ('passport', 'Passport'), ('workPermit', 'Work Permit'), ('militaryId', 'Military ID'), ('driversLicense', "Driver's License")], max_length=20, null=True)),
                ('identification_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('can_manage_properties', models.BooleanField(default=False)),
                ('can_add_units', models.BooleanField(default=False)),
                ('can_edit_units', models.BooleanField(default=False)),
                ('can_delete_units', models.BooleanField(default=False)),
                ('can_view_financial_data', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='property',
            name='manager',
            field=models.ForeignKey(blank=True, limit_choices_to={'user_type': 'MANAGER'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_properties', to='api.profile'),
        ),
        migrations.AlterField(
            model_name='property',
            name='owner',
            field=models.ForeignKey(limit_choices_to={'user_type': 'ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_properties', to='api.profile'),
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
