# Generated by Django 5.1.3 on 2025-05-31 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rentperiodstatus_water_bill_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
