# Generated by Django 5.1.3 on 2025-05-31 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_tenant_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mpesatransaction',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
    ]
