# Generated by Django 5.1.3 on 2024-12-09 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rentpayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lease',
            name='payment_period',
            field=models.CharField(choices=[('MONTHLY', 'Monthly'), ('BIMONTHLY', 'Bi-Monthly'), ('HALF_YEARLY', 'Half Yearly'), ('YEARLY', 'Yearly')], default='MONTHLY', help_text='Rent payment period for this lease', max_length=20),
        ),
    ]
