# Generated by Django 5.1.3 on 2025-06-16 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_mpesastkrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rentperiodstatus',
            name='water_units_used',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Water units used during this period', max_digits=8),
        ),
    ]
