# Generated by Django 5.1.3 on 2025-01-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_profile_user_type_alter_tenant_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='actual_cost',
        ),
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='estimated_cost',
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='repair_cost',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Cost of repair (filled upon completion)', max_digits=10, null=True),
        ),
    ]
