# Generated by Django 5.1.3 on 2025-06-18 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_rentperiodstatus_water_units_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='water_units_used',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Water units consumed this month (defaults to 0 units)', max_digits=8),
        ),
    ]
